### ISSUE TITLE
Tool to browse installed interviews

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALDashboard#119]
Right now, after you install a package, you then have to click around to figure out how to run it. I'm envisioning a tool that just lets you view installed packages and shows you a link to run each of the question YAML files they contain.

**Comment by BryceStevenWilley** [comment]
I like this. A first pass of this would be a directory walk starting at `/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble`, going into every `*/data/questions/*.yml` file and listing them. We'd have to do some simple "does interview have or include a mandatory block", but that'd start taking a while probably. But listing all of those files would be really quick.
