### ISSUE TITLE
Manage users - allow access to developer or new role

### ISSUE THREAD

**Issue by mnewsted** [SuffolkLITLab/docassemble-ALDashboard#128]
Can the Manage user feature be accessible to other users besides admin? We would like to share this great tool with team members without giving them full admin privileges. Please let me know how I can help. Thanks!

**Comment by nonprofittechy** [comment]
@mnewsted do you want this role to be able to do everything you can currently do in the `users` control panel?

**Comment by mnewsted** [comment]
Good question. I don't think download playground files is necessary for this role.  Maybe changing user permissions is also too much. That could get dicey. So for now, just reset password. Thanks!
