### ISSUE TITLE
Other kinds of bugs we could catch in a translation file

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALDashboard#4]
* Extra space at the beginning of a line with a Markdown or Mako keyword, like `####` or `% `
* Lines that are not translated at all or have out of date translation? Will need to re-do the translation script for that.
*  lines with all spaces (indicate pre-formatted text in Markdown--but won't always be a problem)

**Comment by nonprofittechy** [comment]
@plocket as I'm finishing up the translation for UpToCode, these are a few that I ran into. Might be helpful if you're trying to continue working on this.

**Comment by plocket** [comment]
I'll take a look and see what I get done. From what I tested, too many spaces before `%` caused an error, so we probably don't need to cover that one, right?

**Comment by nonprofittechy** [comment]
I trust what you're testing. I only ran into the space before a heading marker (`###`) as an issue. spaces at the beginning of any line are probably not intended but might be unnecessary to test for

**Comment by plocket** [comment]
I don't have time at the moment to wrangle the things here, but I figured I'd at least report in so the work isn't lost.

I've found that the translation checker doesn't have the same kind of behavior as docassemble when working with translation files. This is what I've found so far:
1. Blank cells are ok for docassemble. We may still want to alert the developer to them, but right now we get the below:
```
TypeError: argument of type 'float' is not iterable
In line:   if '$ {' in row['tr_text']:
```
We might want to make a more useful error message for that. The value seems to log as `na`

2. Docassemble just shows improper text for the below, but our mako renderer lists an error:
```
%non-control word with no space at start should get a warning
```
and (basically the same thing)
```
%if with no space and no control syntax should get a warning
```

**Comment by plocket** [comment]
> lines with all spaces (indicate pre-formatted text in Markdown--but won't always be a problem)

Could you describe this a bit more? I can write the code to catch it, I'm just not sure what the message to the user would be.

**Comment by plocket** [comment]
> but our mako renderer lists an error

I thought about it some more. I suppose if our mako renders an error it does at least alert the developer to  a problem, which is better than the opposite. I still think it would be a bit misleading. This difference also makes me a bit concerned about what other differences there are that we haven't caught, but since this is ancillary tool that is just meant for whatever extra help it can give, maybe it isn't as important.

**Comment by nonprofittechy** [comment]
Just to close the loop on this, you said that the behavior is different, but Mako is Mako and our "handling" is just compiling the Mako template, like Docassemble does. I just wanted to clarify that so we don't worry about other undefined differences. I think that framing will be a bit confusing if we add other error handling here. Agreed that we should mark things as "warning" if they render but might not meet developer's expectation. That's a useful distinction.

The problem with empty translation rows really was a bug because I was not handling NaN values properly. Thanks for catching that. My test file just happened to have all of the translations defined, but that's not very realistic to a real world translation file. Fixed in https://github.com/SuffolkLITLab/docassemble-ALDashboard/commit/d34e55d3821828c03942cd33004027e62dcd8af4
