### ISSUE TITLE
id: github PAT  and github owners list - github instructions are not clear enough, how are these? 

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-ALDashboard#49]
@plocket What do you think?

id: github PAT
continue button field: feedback_form_config
question: |
  Use GitHub to collect Feedback and display information on "About" page 
subquestion: |
  Assembly Line uses GitHub to let you:
  1. Let users give feedback about an interview.
  2. Display a "last updated" date on the "About" page of an interview.

  Create a GitHub account that you use **only** 
     -  to add users' feedback to the issues page for each interview, and
     -  to show the last date the interview was updated. This date shows up on the About page that the Assembly Line creates for each interview.
       Note: You **can** use an account that already exists, but we recommend creating an account you use only for these 2 functions. 
  1a. Make the account a member of your organization. Invite the account to join your organization.
  1b. Give the account permission to edit your GitHub organization's repositories. [Set base permissions for members of your organization to **Write.**]  (https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/setting-base-permissions-for-an-organization#setting-base-permissions)
  2. Login to the new account
     2a. Create a Personal Access Token (PAT) for the new account. (https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-token).
      2b. Set the expiration date to "No expiration".
      2c. Tap the checkbox for "repo" permissions.
  3. Copy the token and paste it below
fields:
  - Personal access token: the_config['github issues']['token']
    default: ${ the_config['github issues'].get('token', '') }
---
id: github owners list
continue button field: github_owners_list
question: |
  Avoid GitHub issue spamming
subquestion: |
  To make sure that no one uses the feedback forms to spam just any GitHub repository with issues, you can limit your feedback forms to make issues to repositories owned **only** by specific users or organizations.
      
  List the usernames of all the GitHub users or organizations who own repositories where you will allow users to make issues.
  
  You can list just one if you want.
fields:
  - Usernames[BR](one per line): allowed_github_repo_owners
    datatype: area
    default: |
      ${ "\n".join(the_config['github issues'].get('allowed repository owners',[])) }

**Comment by nonprofittechy** [comment]
The GitHub account does not need to be a member of your organization, and it does not need write access to any particular repositories in my experience, unless you want the issues to be added to a private repository. Issues can be made by anyone on a public repository.

I do think that the `repo` privilege needs to be assigned to the personal access token, but nothing org or repository specific. In fact, it might be best to normally use an account that doesn't have any access to change the repository other than adding issues.

It may be worth pointing out that setting up special membership and write access isn't needed if all of the repos you want feedback to be added to are public.

**Comment by nonprofittechy** [comment]
I think @plocket clarified this in #41 or #42
