### ISSUE TITLE
id: github owners default - I am not sure what this means

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-ALDashboard#50]
@plocket 
"choose a default repository owner so that interviews don't have to each list their own"
If the interviews are all transferred to the organization wouldn't the organization be the owner... or is this metadata?

---
id: github owners default
continue button field: github_owners_default
question: |
  Default GitHub repository owner
subquestion: |
  Finally, you can also choose a default repository owner so that interviews don't have to each list their own. Pick one of the usernames to be the default repository owner.
fields:
  - Default account name: the_config['github issues']['default repository owner']
    input type: radio
    code: |
      the_config['github issues'].get('allowed repository owners', [])
---

**Comment by nonprofittechy** [comment]
I think @plocket clarified this in #41 or #42
