### ISSUE TITLE
Remove dependency on ALToolbox

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-ALDashboard#61]
The `install_assembly_line` interview [depends on ALToolbox's collapse template](https://github.com/SuffolkLITLab/docassemble-ALDashboard/blob/79fb5f4fc469dceeebd0877a030072185479736c/docassemble/ALDashboard/data/questions/install_assembly_line.yml#L4). Ironically, this is the one interview that users will likely install first and then use to install the rest of the Assembly Line (including ALToolbox), so we probably don't want to make them install the ALToolbox as well.

Our options:
* add ALToolbox to `setup.py`, so when ALDashboard is installed ALToolbox is automatically installed
* remove the dependency on ALToolbox, either by
    * changing the collapsed template to a `help` tab, or
    * copying the Bootstrap needed to make a collapsible template
    
I'm leaning towards just copying the bootstrap needed to make the collapsible template, given it's only used once in the file.

**Comment by nonprofittechy** [comment]
Let's just copy the bootstrap
